version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash
    stdin_open: true
    tty: true
    environment:
      PYTHONPATH: /home/python/app/mock
    volumes:
      - .:/home/python/app
