version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: tkislan/kodi-simulator
        name: kodi
    environment:
        KODI_HOST: http://kodi:8080
    working_directory: ~/app
    steps:
      - checkout

      - run:
          name: Set PYTHONPATH environment variable
          command: echo 'export PYTHONPATH=${HOME}/app/mock:${HOME}/app/resources/lib:${HOME}/app/resources/connect' >> $BASH_ENV

      - run:
          name: Export
          command: export

      - run:
          name: Install dependencies
          command: ./install-dependencies.sh

      - run:
          name: Wait for kodi simulator
          command: ./wait-for-kodi-simulator.sh

      - run:
          name: Run tests
          command: python -m unittest discover -s resources/connect/tests/
